package app.nexus.android

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool

/**
 * UI sounds (res/raw, generated by scripts/gen-sounds.mjs). SoundPool keeps
 * the decoded clips in memory, so playback starts without delay.
 */
class SoundPlayer(context: Context) {
    private val clips = mapOf(
        "join" to R.raw.join,
        "leave" to R.raw.leave,
        "mute" to R.raw.mute,
        "unmute" to R.raw.unmute,
        "deafen" to R.raw.deafen,
        "undeafen" to R.raw.undeafen,
        "screen_start" to R.raw.screen_start,
        "screen_stop" to R.raw.screen_stop,
        "message" to R.raw.message,
        "ring" to R.raw.ring,
        "calling" to R.raw.calling,
    )
    private val pool = SoundPool.Builder()
        .setMaxStreams(4)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_ASSISTANCE_SONIFICATION)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build(),
        )
        .build()
    private val ids = clips.mapValues { (_, res) -> pool.load(context, res, 1) }
    private val loops = mutableMapOf<String, Int>()

    fun play(name: String, volume: Float) {
        val id = ids[name] ?: return
        pool.play(id, volume, volume, 1, 0, 1f)
    }

    @Synchronized
    fun startLoop(name: String, volume: Float) {
        if (loops.containsKey(name)) return
        val id = ids[name] ?: return
        val stream = pool.play(id, volume, volume, 2, -1, 1f)
        if (stream != 0) loops[name] = stream
    }

    @Synchronized
    fun stopLoop(name: String) {
        loops.remove(name)?.let { pool.stop(it) }
    }

    fun release() {
        pool.release()
    }
}
