import { settings } from "./settings";

/** Generated by scripts/gen-sounds.mjs into public/sounds. */
export type Sound =
  | "join"
  | "leave"
  | "mute"
  | "unmute"
  | "deafen"
  | "undeafen"
  | "screen_start"
  | "screen_stop"
  | "message"
  | "ring"
  | "calling";

type SinkAudio = HTMLAudioElement & { setSinkId?: (id: string) => Promise<void> };

function element(name: Sound, loop: boolean): SinkAudio {
  const s = settings();
  const el: SinkAudio = new Audio(`/sounds/${name}.wav`);
  el.loop = loop;
  el.volume = Math.min(1, Math.max(0, s.soundVolume));
  if (s.outputDeviceId && s.outputDeviceId !== "default") void el.setSinkId?.(s.outputDeviceId).catch(() => undefined);
  return el;
}

/** Plays a short UI sound (no-op when sounds are off). */
export function playSound(name: Sound): void {
  if (!settings().sounds) return;
  void element(name, false)
    .play()
    .catch(() => undefined);
}

const loops = new Map<Sound, SinkAudio>();

/** Starts a looping sound (ring, calling) until stopLoop; idempotent. */
export function startLoop(name: Sound): void {
  if (!settings().sounds || loops.has(name)) return;
  const el = element(name, true);
  loops.set(name, el);
  void el.play().catch(() => loops.delete(name));
}

export function stopLoop(name: Sound): void {
  const el = loops.get(name);
  if (!el) return;
  loops.delete(name);
  el.pause();
  el.removeAttribute("src");
  el.load();
}
