import { create } from 'zustand';
import { NexusNative } from '../native/NexusNative';

/** res/raw clips generated by scripts/gen-sounds.mjs (played by SoundPool). */
export type Sound =
  | 'join'
  | 'leave'
  | 'mute'
  | 'unmute'
  | 'deafen'
  | 'undeafen'
  | 'screen_start'
  | 'screen_stop'
  | 'message'
  | 'ring'
  | 'calling';

interface SoundPrefs {
  enabled: boolean;
  volume: number;
  set: (patch: Partial<Pick<SoundPrefs, 'enabled' | 'volume'>>) => void;
}

export const useSoundPrefs = create<SoundPrefs>()((set, get) => ({
  enabled: true,
  volume: 0.6,
  set: (patch) => {
    set(patch);
    const { enabled, volume } = get();
    void NexusNative.setPref('sounds', JSON.stringify({ enabled, volume })).catch(() => undefined);
  },
}));

export async function loadSoundPrefs(): Promise<void> {
  const raw = await NexusNative.getPref('sounds').catch(() => null);
  if (!raw) return;
  try {
    const p = JSON.parse(raw) as { enabled?: boolean; volume?: number };
    useSoundPrefs.setState({ enabled: p.enabled ?? true, volume: p.volume ?? 0.6 });
  } catch {
    // ignore corrupted prefs
  }
}

export function playSound(name: Sound): void {
  const { enabled, volume } = useSoundPrefs.getState();
  if (enabled) void NexusNative.playSound(name, volume).catch(() => undefined);
}

export function startLoop(name: Sound): void {
  const { enabled, volume } = useSoundPrefs.getState();
  if (enabled) void NexusNative.startSoundLoop(name, volume).catch(() => undefined);
}

export function stopLoop(name: Sound): void {
  void NexusNative.stopSoundLoop(name).catch(() => undefined);
}
